### PR TITLE
Add support for git lfs

### PR DESCRIPTION
**Pull request by bobbymart1n**

### CODE REVIEW

**Comment by bobbymart1n** [comment]
@drdanz I can't seem to request your review on this PR, should I request someone in the Robotology org?

**Review by drdanz — APPROVED** [review]
LGTM. Thanks!

**Comment by drdanz** [comment]
Merged, thanks!

**Comment by bobbymart1n** [comment]
Thanks so much!!

**Comment by drdanz** [comment]
Thank you for contributing :-)

**Pull request merged**
